apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: democolgate-demo
spec:
  gateway: kyma-system/kyma-gateway
  hosts:
    - democolgate-demo.c86fefc.kyma.ondemand.com
  service:
    name: democolgate-demo
    port: 80
  rules:
    - path: /.*
      methods: ["GET","POST"]
      noAuth: true
