apiVersion: apps/v1
kind: Deployment
metadata:
  name: democolgate-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: democolgate-demo
  template:
    metadata:
      labels:
        app: democolgate-demo
    spec:
      containers:
        - name: demo
          image: REPLACE_ME
          ports:
            - containerPort: 80
